# This is a basic workflow to help you get started with Actions

name: 01 - environments test 

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy_test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: deploy
        run: |
          echo "This is my Secret: ${{ secrets.SECRET_1 }}"

  deploy_prod:
    needs: deploy_test
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: deploy
        run: |
          echo "This is my Secret: ${{ secrets.SECRET_1 }}"
